### PR TITLE
fix(accordionitemheader): #102 - Swap ToggleOpen Button for an Icon

### PR DESCRIPTION
**Pull request by JoelJKoel**
Swapped the ToggleOpen Button which was used in AccordionItemHeader for an Icon which looks and handles the same getting rid of the nested interactions. 

image

### CODE REVIEW

**Comment by airikej** [comment]
@kasparsuvi1 would like second opinion

**Comment by kasparsuvi1** [comment]
Is it needed because AccordionHeader has `role="button"`  and includes button (ToggleOpen) which is invalid html?
Maybe we could use ToggleOpen as not button in that case. Because currently the openText/closeText/isHovered etc funcionality is removed (also props arent). And the ToggleOpen functionality is duplicated to two places.
In summary i can see the problem, but not sure if this is the way to go. And if  we go with this approach, then the PR needs some improvement.

**Comment by JoelJKoel** [comment]
Jah, vahepeal sattusid need tõesti kokku. Aga nagu arutasime peaks ilmselt teisiti lähenema sellele probleemile. Kas proovin ise ToggleOpen komponenti ringi teha et see poleks button või saate te ise mingi hetk sellele peale vaadata?

**Comment by airikej** [comment]
Ma ütleks nii, et kui sellele on vajadus, siis proovi lahendus leida praegu - hetkel raske öelda, millal Accordion Tedi-sse tuleb, sest hetkel pole sellele disainigi.

**Pull request merged**
